name: Daily Export

on:
  schedule:
    - cron: "5 0 * * *"   # Runs every day at 00:05 UTC
  workflow_dispatch:       # Allows manual trigger via the Actions tab

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch CSV from Render
        run: |
          DAY="$(date -u +%F)"
          OUT="clicks_${DAY}.csv"
          URL="https://tiny-fob-next.onrender.com/admin/export/day?day=${DAY}"
          echo "Fetching ${URL}"
          curl -sS -L -H "X-Admin-Pass: $FOB_ADMIN_PASS" "$URL" -o "$OUT"
          echo "Saved $OUT"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-clicks
          path: clicks_*.csv

    env:
      FOB_ADMIN_PASS: ${{ secrets.FOB_ADMIN_PASS }}
